---
name: Checks

on: [push]

jobs: 
  test-lint:
  #this is the id of the job that you use to reference the job when creating workflows
    name: Test and Lint
    #this is the name of the job that will show up in the actions tab
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
        #this is the action that checks out the code from the repo
        #check out means to download the code from the repo
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
    # now we have a compelte set of steps to run our tests and linting
